### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Yamuna88** [abarcel/iris#2]

**Comment by abarcel** [comment]
Hello,

```
from src.daugman_iris_edge_detection import DIED

_, info = DIED(example_img).results()
```

Will give the information requested and return  [x, y, differential_value, radius].
I'm aware that it is not documented, so it is not really simple to see.

**Comment by Yamuna88** [comment]
Hi sir,
    I got the answer. Tats y i deleted my question. But anyway, thanks for
ur support.

**Comment by Yamuna88** [comment]
Hi sir, first of all thanks for your quick response. I have one more doubt.
Here we are getting the x,y,range and radius value. but it was captured,
depending upon the image pix iris value.

I wish to get the diameter of Iris from pixel in mm(millimeter) format..

Here my code is,

cv2.circle(eye_ch, (circle_val[1] * 14, circle_val[0] * 14), circle_val[3]
* 14, (0,255,0),5) //like, we draw the circle for against the frame size.

radi_circle = circle_val[3]; //iris radius
print("radi_circle (pix): " ,radi_circle);
dia_circle = circle_val[3]*2;
print("dia_circle (pix) : " ,dia_circle); //finding the iris diameter
dia_circle_MM=dia_circle/3.7795275591; //converting the image pix value to
mm(millimetre)
print("dia_circle_MM (mm) : " ,dia_circle_MM);

Whatever it is, When I load any image the iris diameter comes under 10mm to
11mm.

I thought, I have to do some conversion to find out the diameter value for
all images.

If you have any idea, can you please help with this.



Thanks,
Yamuna.
